name: "clear-image-action"
author: yiyungent
description: "Clean up unreferenced images. | 清理未引用图片"


inputs:
  # gh_token:
  #   description: "GitHub access token with Repo scope"
  #   default: ${{ github.token }}
  #   required: true

  # repository:
  #   description: "Your GitHub repository"
  #   default: ${{ github.repository }}
  #   required: false

  scan_directory:
    description: "scan directory (md, html, images)"
    default: ""
    required: false

  ignore_paths:
    description: "ignore paths"
    default: ""
    required: false
  
  # TODO: 未使用, 直接使用回到覆盖, 不方便识别默认base分支
  base:
    description: "base branch for create-pull-request. | Sets the pull request base branch."
    default: ""
    required: false

  cia_debug:
    description: "debug for clear-image-action"
    default: false
    required: false


outputs:
  image_report_clear:
    description: "image report: clear"
    value: ${{ steps.run-tool-cimg.outputs.image_report }}

  image_report_check:
    description: "image report: check"
    value: ${{ steps.run-tool-fimg.outputs.image_report }}


runs:
  using: "composite"
  steps:

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    
    - name: Install tool
      # The command you want to run. This can be inline or a script in your action repository:
      # ${{ github.action_path }} or $GITHUB_ACTION_PATH
      # run: ${{ github.action_path }}/test/script.sh
      run: | 
        dotnet tool install -g coo
        coo --version
      shell: bash
    
    - name: Run tool cimg
      id: run-tool-cimg
      run: |
        export INPUT_CIA_DEBUG=${{ inputs.cia_debug }}
        # coo cimg --github-action -d --ignore-paths='${{ inputs.ignore_paths }}' "F:\Com\me\Repos\notebook\source\_posts"
        # 注意: 是 workspace 而不是 action_path, action_path 一定指向 clear-image-action. 而不是 workspace 指向正在使用此action的仓库根目录
        coo cimg --github-action -d --ignore-paths='${{ inputs.ignore_paths }}' ${{ github.workspace }}/${{ inputs.scan_directory }}
      shell: bash

    - name: The content must be escaped to preserve newlines.
      id: get-body-cimg
      run: |
        cimg_body="${{ steps.run-tool-cimg.outputs.image_report }}"
        # ${string//substring/replacement} # 使用$replacement, 代替所有匹配的$substring
        cimg_body="${cimg_body//'%'/%25}"
        cimg_body="${cimg_body//'\n'/%0A}"
        cimg_body="${cimg_body//'\r'/%0D}" 
        echo ::set-output name=cimg_body::$cimg_body
      shell: bash

    - name: Run tool fimg
      id: run-tool-fimg
      run: |
        export INPUT_CIA_DEBUG=${{ inputs.cia_debug }}
        coo fimg --github-action --ignore-paths='${{ inputs.ignore_paths }}' ${{ github.workspace }}/${{ inputs.scan_directory }}
      shell: bash

    - name: The content must be escaped to preserve newlines.
      id: get-body-fimg
      run: |
        fimg_body="${{ steps.run-tool-fimg.outputs.image_report }}"
        # ${string//substring/replacement} # 使用$replacement, 代替所有匹配的$substring
        fimg_body="${fimg_body//'%'/%25}"
        fimg_body="${fimg_body//'\n'/%0A}"
        fimg_body="${fimg_body//'\r'/%0D}" 
        echo ::set-output name=fimg_body::$fimg_body
      shell: bash

    # 注意: 最后 先 Create issue 再 Create Pull Request, 防止没有文件变化时, Create Pull Request 失败而中途退出

    - name: Create issue
      uses: actions-cool/issues-helper@v2
      with:
        actions: 'create-issue'
        token: ${{ github.token }} # 注意: 不是 ${{ github.GITHUB_TOKEN }}
        title: '[clear-image-action] Update report: fimg'
        body: ${{ steps.get-body-fimg.outputs.fimg_body }}
        # 注意:此 action: labels 支持多个，需用逗号隔开
        labels: 'image-report,automated issue'

    # Make changes to pull request here
    # https://github.com/peter-evans/create-pull-request
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "[clear-image-action] cimg"
        branch: clear-image-action/report
        delete-branch: true
        branch-suffix: "short-commit-hash"
        title: '[clear-image-action] Update report: cimg'
        body: ${{ steps.get-body-cimg.outputs.cimg_body }}
        labels: |
          image-report
          automated pr




branding:
  icon: "image"
  color: "green"
